### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.ClassVisitor, but class was expected

### ISSUE THREAD

**Issue by iphydf** [abstractj/kalium#39] opened 2015-10-28 18:08 UTC
I cannot use kalium at all:
```
java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.ClassVisitor, but class was expected
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:74)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:265)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:244)
	at org.abstractj.kalium.NaCl$SingletonHolder.<clinit>(NaCl.java:41)
	at org.abstractj.kalium.NaCl.sodium(NaCl.java:28)
[...]
```

**Comment by abstractj** [comment] 2015-12-18 05:21
@iphydf could you please post the steps to reproduce your issue? Plus, your environment: OS, libsodium version, Java version...

**Comment by abstractj** [comment] 2016-05-14 05:07
@iphydf closing it right now, but feel free to reopen if you have the steps to reproduce.

**Closed by abstractj** 2016-05-14 05:07 UTC

**Comment by rf-** [comment] 2016-06-25 02:03
I'm seeing this problem as a side effect of adding `asm` 3.1 as a dependency, which was a side effect of adding `finagle-stats` as a dependency. Repro project here: https://gist.github.com/rf-/eb31bc57b21b766c68ecbbdfc2322f8b

It seems pretty resilient to details of environment. I've been able to repro both on a Mac and in a Docker image based on the `java:8-jdk` image. The Mac has libsodium 1.0.10, not sure about the Docker image.

**Comment by rf-** [comment] 2016-06-25 02:05
Oh, it looks like there's a version conflict that SBT didn't report because the `asm` package's organization has changed?

**Comment by rf-** [comment] 2016-06-25 02:12
Ugh. Seems like this is really not your fault and also like it's going to be really annoying to fix. A bunch of the Twitter stuff indirectly depends on this old version of `asm`. 😢  Any ideas?

**Comment by rf-** [comment] 2016-06-25 02:25
For anyone else who has the same problem and comes across this issue, the fix was adding an `excludeAll` call to `build.sbt`:

```
  "com.twitter" %% "finagle-stats" % "6.35.0" excludeAll(
    ExclusionRule(organization = "asm")
  ),
```

This should be fine as long as the libraries that depend on `asm` 3.1 can also handle 4.0.
